platform :ios, '13.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
project 'Runner', {'Debug'=>'Debug','Profile'=>'Release','Release'=>'Release'}
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..','Flutter','Generated.xcconfig'), __FILE__)
  raise "Run flutter pub get first" unless File.exist?(generated_xcode_build_settings_path)
  File.foreach(generated_xcode_build_settings_path) { |line| return $1.strip if line =~ /FLUTTER_ROOT\=(.*)/ }
end
require File.expand_path(File.join('packages','flutter_tools','bin','podhelper'), flutter_root)
flutter_ios_podfile_setup
target 'Runner' do
  use_frameworks!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
post_install { |installer| installer.pods_project.targets.each { |target| flutter_additional_ios_build_settings(target) } }
