import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { AnalysisCard } from '../../src/components/AnalysisCard';
import { BrandHeader } from '../../src/components/BrandHeader';
import { Card } from '../../src/components/Card';
import { Screen, SectionHeader } from '../../src/components/Screen';
import { useAnalysis } from '../../src/features/analysis/AnalysisContext';
import { normalizeSymbol } from '../../src/features/analysis/normalization';
import { colors } from '../../src/theme/colors';

const intervals = ['15m', '1h', '4h', '1d'] as const;
const quickSymbols = ['BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'BNBUSDT'];
export default function HomeScreen() {
  const [symbol, setSymbol] = useState('BTCUSDT'); const [interval, setInterval] = useState('1h');
  const analysis = useAnalysis();
  const analyze = (value = symbol) => { const normalized = normalizeSymbol(value); setSymbol(normalized); if (normalized) void analysis.analyze(normalized, interval); };
  return <Screen><BrandHeader /><SectionHeader title="Piyasa özeti" subtitle="Veriyi seç, sinyali saniyeler içinde değerlendir." /><Card style={styles.stats}><View style={styles.stat}><Text style={styles.statValue}>7/24 Açık</Text><Text style={styles.statLabel}>Kripto</Text></View><View style={styles.stat}><Text style={styles.statValue}>BINANCE</Text><Text style={styles.statLabel}>Kaynak</Text></View><View style={styles.stat}><View style={styles.liveRow}><View style={styles.liveDot} /><Text style={styles.statValue}>İstek anında</Text></View><Text style={styles.statLabel}>Son kapanmış mum</Text></View></Card><View style={styles.inputWrap}><Ionicons name="search" size={21} color={colors.muted} /><TextInput accessibilityLabel="Varlık sembolü" autoCapitalize="characters" value={symbol} onChangeText={setSymbol} onSubmitEditing={() => analyze()} placeholder="Örn. BTCUSDT" placeholderTextColor={colors.muted} style={styles.input} /></View><View style={styles.row}>{intervals.map((item) => <Pressable key={item} onPress={() => setInterval(item)} style={[styles.chip, interval === item && styles.chipActive]}><Text style={[styles.chipText, interval === item && styles.chipTextActive]}>{item}</Text></Pressable>)}</View><Pressable disabled={analysis.status === 'loading'} onPress={() => analyze()} style={({ pressed }) => [styles.button, pressed && styles.pressed, analysis.status === 'loading' && styles.disabled]}><Ionicons name="analytics" size={20} color={colors.black} /><Text style={styles.buttonText}>Analiz et</Text></Pressable><View style={styles.quickWrap}>{quickSymbols.map((item) => <Pressable key={item} onPress={() => analyze(item)} style={styles.quick}><Text style={styles.quickText}>{item}</Text></Pressable>)}</View>{analysis.status === 'loading' ? <Card style={styles.stateCard}><ActivityIndicator color={colors.primary} size="large" /><Text style={styles.stateTitle}>Piyasa analiz ediliyor…</Text><Text style={styles.stateBody}>Teknik göstergeler hesaplanıyor.</Text></Card> : analysis.status === 'error' ? <Card style={styles.stateCard}><Ionicons name="cloud-offline-outline" size={44} color={colors.danger} /><Text style={styles.stateTitle}>Analiz alınamadı</Text><Text style={styles.stateBody}>{analysis.message}</Text><Pressable onPress={() => analyze()} style={styles.retry}><Ionicons name="refresh" size={18} color={colors.primary} /><Text style={styles.retryText}>Yeniden dene</Text></Pressable></Card> : analysis.data ? <AnalysisCard analysis={analysis.data} onRefresh={() => analyze(analysis.data?.symbol)} /> : <Card style={styles.stateCard}><Ionicons name="pulse-outline" size={44} color={colors.muted} /><Text style={styles.stateTitle}>Henüz analiz yok</Text><Text style={styles.stateBody}>Bir sembol seçip “Analiz et” düğmesine dokunun.</Text></Card>}</Screen>;
}
const styles = StyleSheet.create({ stats: { flexDirection: 'row', justifyContent: 'space-around', paddingVertical: 20 }, stat: { alignItems: 'center', gap: 5 }, statValue: { color: colors.primary, fontSize: 13, fontWeight: '800' }, statLabel: { color: colors.muted, fontSize: 12 }, liveRow: { flexDirection: 'row', alignItems: 'center', gap: 5 }, liveDot: { width: 7, height: 7, borderRadius: 5, backgroundColor: colors.primary }, inputWrap: { height: 56, borderRadius: 14, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, gap: 9 }, input: { flex: 1, height: '100%', color: colors.text, fontSize: 16 }, row: { flexDirection: 'row', gap: 8 }, chip: { flex: 1, alignItems: 'center', paddingVertical: 10, borderRadius: 12, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, chipActive: { backgroundColor: colors.primaryDark, borderColor: colors.primary }, chipText: { color: colors.muted, fontWeight: '700' }, chipTextActive: { color: colors.primary }, button: { height: 54, borderRadius: 14, backgroundColor: colors.primary, flexDirection: 'row', gap: 8, justifyContent: 'center', alignItems: 'center' }, buttonText: { color: colors.black, fontSize: 16, fontWeight: '900' }, pressed: { opacity: 0.8 }, disabled: { opacity: 0.55 }, quickWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, quick: { backgroundColor: colors.surfaceRaised, borderRadius: 18, paddingHorizontal: 12, paddingVertical: 8, borderWidth: 1, borderColor: colors.border }, quickText: { color: colors.text, fontSize: 12, fontWeight: '600' }, stateCard: { alignItems: 'center', gap: 9, paddingVertical: 28 }, stateTitle: { color: colors.text, fontWeight: '800', fontSize: 17 }, stateBody: { color: colors.muted, textAlign: 'center', lineHeight: 20 }, retry: { flexDirection: 'row', gap: 6, padding: 8 }, retryText: { color: colors.primary, fontWeight: '700' } });
