import { Ionicons } from '@expo/vector-icons';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import type { Analysis, SignalAction } from '../types/analysis';
import { colors } from '../theme/colors';
import { Card } from './Card';

const actionDetails: Record<SignalAction, { label: string; color: string }> = { SAFE_BUY: { label: 'GÜVENLİ AL', color: colors.primary }, TAKE_PROFIT: { label: 'KÂR AL', color: colors.danger }, HOLD: { label: 'BEKLE', color: colors.blue }, UNKNOWN: { label: 'BİLİNMİYOR', color: colors.muted } };
export function AnalysisCard({ analysis, onRefresh }: { analysis: Analysis; onRefresh: () => void }) {
  const detail = actionDetails[analysis.action];
  const date = analysis.signal_time ? new Date(analysis.signal_time).toLocaleString('tr-TR') : 'Bilinmiyor';
  return <Card style={styles.card}><View style={styles.top}><View><Text style={styles.symbol}>{analysis.symbol} • {analysis.timeframe}</Text><Text style={styles.price}>${analysis.price.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</Text></View><View style={[styles.badge, { backgroundColor: `${detail.color}22` }]}><Text style={[styles.badgeText, { color: detail.color }]}>{detail.label}</Text></View></View><View style={styles.divider} /><Text style={styles.label}>Sinyal gücü: <Text style={{ color: detail.color }}>{Math.round(analysis.confidence * 100)}%</Text></Text><View style={styles.progress}><View style={[styles.progressValue, { width: `${analysis.confidence * 100}%`, backgroundColor: detail.color }]} /></View><Text style={styles.heading}>Analiz nedenleri</Text>{analysis.reasons.map((reason) => <View key={reason} style={styles.reason}><Ionicons name="checkmark-circle-outline" size={20} color={detail.color} /><Text style={styles.reasonText}>{reason}</Text></View>)}<Text style={styles.date}>Son güncelleme: {date}</Text><Pressable accessibilityRole="button" onPress={onRefresh} style={styles.refresh}><Ionicons name="refresh" size={18} color={colors.primary} /><Text style={styles.refreshText}>Yenile</Text></Pressable></Card>;
}
const styles = StyleSheet.create({ card: { gap: 12 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, symbol: { color: colors.muted, fontSize: 14 }, price: { color: colors.text, fontSize: 28, fontWeight: '800', marginTop: 4 }, badge: { borderRadius: 20, paddingHorizontal: 12, paddingVertical: 8 }, badgeText: { fontSize: 12, fontWeight: '800' }, divider: { height: 1, backgroundColor: colors.border }, label: { color: colors.text, fontSize: 15 }, progress: { height: 7, borderRadius: 8, backgroundColor: colors.border, overflow: 'hidden' }, progressValue: { height: '100%', borderRadius: 8 }, heading: { color: colors.text, fontWeight: '700', fontSize: 16, marginTop: 4 }, reason: { flexDirection: 'row', alignItems: 'center', gap: 9 }, reasonText: { color: colors.text, flex: 1 }, date: { color: colors.muted, fontSize: 12, marginTop: 4 }, refresh: { alignSelf: 'flex-end', flexDirection: 'row', gap: 6, alignItems: 'center', padding: 5 }, refreshText: { color: colors.primary, fontWeight: '700' } });
